### ISSUE TITLE
Download button

### ISSUE THREAD

**Issue by hogyoku** [yandevelop/Bea#1]
Would it be posible to add a download button for the posts? I have a older tweaked bereal version that has that.

**Comment by yandevelop** [comment]
That should already be present. Are you using the ipa or the deb?

**Comment by RobyRew** [comment]
> That should already be present. Are you using the ipa or the deb?

downloading is posible.

Im wondering if you have some time to update the tweak because it freaks out with the new view they added and also with multiple posts, 

If not i might push a pull request with an update next week, let me know what are your plans sir! 😎
