### ISSUE TITLE
Unable to install | please try again later

### ISSUE THREAD

**Issue by gabreeele** [yandevelop/Bea#10]
![photo_2023-06-15_19-46-03](https://github.com/yandevelop/Bea/assets/94537157/917c5479-70fa-4571-abbb-1b997423794e)
As you can see from the screenshot installation failed after i try to sideload the .ipa file via altstore

**Comment by yandevelop** [comment]
I don't think this is an error of Bea. Please refer to https://faq.altstore.io/getting-started/troubleshooting-guide. If you got further issues please reach out to me again
