### ISSUE TITLE
Support for 14 Pro ?

### ISSUE THREAD

**Issue by adriengonz** [yandevelop/Bea#12]
Unable to install app, Probably because 14 Pro is not supported (see Attachement picture)
![Capture d’écran   2023-06-28 à 12 18 18](https://github.com/yandevelop/Bea/assets/40824310/a7058817-95ec-47a9-8206-0bbbae9adbeb)

**Comment by hogyoku** [comment]
Works fine on my 14promax with appdb

**Comment by adriengonz** [comment]
Update, I had unzip ipa file and modified the "info.plist" for add iPhone15,2 value to SupportedDevices
I rezip and rename zip in .ipa, and app has been successfully installed.

**Comment by adriengonz** [comment]
No problems, thanks !
