### ISSUE TITLE
Screenshot preventing didn't work + post BeReal with camera roll

### ISSUE THREAD

**Issue by adriengonz** [yandevelop/Bea#14]
Hi, Just to let you know, the screenshot preventing obviously didn't work (I'm on iPhone 14 Pro with iOS 17.0).

And how to post bereal with camera roll ? That is, with photos from his gallery (I don't have button or other options)

Thanks in advance,

Adrien

**Comment by yandevelop** [comment]
Hi, thanks for reporting. I'll check the screenshot thing asap. Instead of screenshooting you can also directly download the image of the BeReal. You can post BeReals from your camera roll by tapping the "BeFake" logo at the top of the screen in BeReal.

**Comment by adriengonz** [comment]
Hi, oh right, I thought the "Befake" logo at the top was just to show that it was the tweaked version of bereal.
Thanks for the information

**Comment by yandevelop** [comment]
You're welcome. I dont know where else to put that "button". I thought its pretty well accessible, but if you got any ideas I'd be happy to hear them! :))

**Comment by yandevelop** [comment]
Would you be able to test screenshot detection and new features with a build i would send you? If so, please add me on Discord (@yandevelop). Thanks
