### ISSUE TITLE
Fake Post isn’t working

### ISSUE THREAD

**Issue by matskobinks** [yandevelop/Bea#16]
![631ADC3D-3338-49CE-A071-BB228C331B78](https://github.com/yandevelop/Bea/assets/86472519/d9423416-9c35-4f01-93c8-3376296e52df)

**Comment by yandevelop** [comment]
Thanks for reporting. The API is rejecting the request. It's probably because you haven't set a front image. If that still doesn't work it could be because of the Retake count being too high. Please try it with "normal" values.

**Comment by matskobinks** [comment]
you were right! it’s working

**Comment by yandevelop** [comment]
Great! What was it that fixed it? The retake count or the front image missing?

**Comment by matskobinks** [comment]
i tried both on the same time, so I don't know

**Comment by matskobinks** [comment]
if we look closely on the screen, i had a front image, its just dark but we can see the pixels. so its the retake number
