### ISSUE TITLE
No notifications

### ISSUE THREAD

**Issue by Lanneer487** [yandevelop/Bea#19]
I have a problem with the notifications on my iPhone. I don’t get a notifications when it’s time to be real. 
Everything is turned on in the app and also in my device settings. 
Is there a solution of this problem?

**Comment by yandevelop** [comment]
Bea is not the cause of this problem, it's BeReal's fault. There's several people on [r/bereal_app](https://www.reddit.com/r/bereal_app/) having the same problems. I occasionally also do not get notifications.

**Comment by hogyoku** [comment]
I think it depends on your signing app as well. Not all signing services support notifications
