### ISSUE TITLE
Add download button to friends of friends / discovery

### ISSUE THREAD

**Issue by hogyoku** [yandevelop/Bea#2]
Hey loving this great mod. But was wondering if it's posible to add the download button to friends of friends and discovery?

**Comment by yandevelop** [comment]
Idk what you mean by friends of friends (do you mean Realmojis?), but the issue with the download button for Discovery feed is already known and will be fixed in the next version :)

**Comment by hogyoku** [comment]
![IMG_0267](https://github.com/yandevelop/Bea/assets/3275546/22463b2d-648d-484d-922e-d72c647a55a4)

I just think that this is how the new discovery feed is.

**Comment by yandevelop** [comment]
Thanks, sadly the "Friends of Friends" feed is not yet available for me. I will push an update that adds the download button to that feed as soon as I am able to do so :)

**Comment by hogyoku** [comment]
Any possibility to add the download function to people's reaction on your own bereal?

**Comment by hogyoku** [comment]
With any version higher than [1.3](https://github.com/yandevelop/Bea/releases/tag/1.3) the download botton disapears for the My Friends list its still there with friends of friends. I have this problem with my ipad and iphone 

![IMG_6644](https://github.com/yandevelop/Bea/assets/3275546/a522e954-80e7-429a-84d1-d052a218edeb)
![IMG_6642](https://github.com/yandevelop/Bea/assets/3275546/c67f8dd4-d6ff-4aad-85d8-808844545293)
