### ISSUE TITLE
The app still crash when I try to open

### ISSUE THREAD

**Issue by smule98** [yandevelop/Bea#26]
iPhone 14 pro
The app crash when I try to open since September.
Any update? 
thanks

**Comment by smule98** [comment]
I've installed BeReal 1.16.1 + Bea 1.3.2 ipa with sideloadly.
Bea installs correctly, when I try to open it after 6/7 seconds of loading crashes.
iPhone 14 pro with ios 16.6.1

**Comment by yandevelop** [comment]
Without any additional information I can't help. Do you got any crash log? Does it happen consequently?

**Comment by smule98** [comment]
[BeReal-2023-11-06-221011.txt](https://github.com/yandevelop/Bea/files/13289851/BeReal-2023-11-06-221011.txt)

That’s the log file. Yes it happens every time, I can’t open the app

**Comment by smule98** [comment]
Normal BeReal from AppStore is already installed and it opens correctly

**Comment by yandevelop** [comment]
hmm alright thanks

**Comment by yandevelop** [comment]
The issue apparently is that the app or tweak is trying to access a string that is null and thus crashes. I have added checks for that in the tweak now but I currently can't inject it into the ipa. If you can inject, here's the deb file: https://easyupload.io/pix2w3

**Comment by smule98** [comment]
Thank you for the assistance.
Can I inject the deb only if the iPhone is jailbroken?

**Comment by yandevelop** [comment]
No, some side loading services allow injecting the deb into a decrypted ipa. I guess sideloadly can do it iirc. You need the decrypted BeReal ipa and the deb I provided.

**Comment by smule98** [comment]
> The issue apparently is that the app or tweak is trying to access a string that is null and thus crashes. I have added checks for that in the tweak now but I currently can't inject it into the ipa. If you can inject, here's the deb file: https://easyupload.io/pix2w3

Can you re-upload the deb file? And can I inject in your latest ipa? Thank you

**Comment by yandevelop** [comment]
The attempted fix that was included in the deb i uploaded there is also in the latest release of Bea, so please try that. I had another person testing but apparently the issue is still not fixed and we tried injecting a tweak where no code was executed. Still, the infinite loading issue remained

**Comment by smule98** [comment]
Ah ok, yes in fact I had tried to install the 1.3.3 release but it still crashes after a loading of 7/8 seconds

**Comment by yandevelop** [comment]
Sadly no, it seems that BeReal crashes as soon as any deb is being injected regardless of if code is being hooked or not. I currently don't have time to investigate into this further

**Comment by smule98** [comment]
> Sadly no, it seems that BeReal crashes as soon as any deb is being injected regardless of if code is being hooked or not. I currently don't have time to investigate into this further

Hi my friend, i've tried the newer version of 2 days ago... same result
I've tried next to inject the deb file in your bea.ipa... same result
