### ISSUE TITLE
Cannot sign in on sideloaded IPA

### ISSUE THREAD

**Issue by michaljedrr** [yandevelop/Bea#37]
Cannot sign in after putting a sms code, it shows internal error. Probably some API stuff, because same stuff happening on toofake or befake

**Comment by MiholS** [comment]
Same pls fix

**Comment by yandevelop** [comment]
Please see #24

**Comment by MiholS** [comment]
so impossible for jailed devices and not trollstore compatible

**Comment by michaljedrr** [comment]
Now I am just getting bad request #400 error. Only with my phone number. Can't even log in on the official BeReal app

**Comment by MiholS** [comment]
You have probably been banned

**Comment by michaljedrr** [comment]
Fr? What could be the reason lol
