### ISSUE TITLE
Bereal not working

### ISSUE THREAD

**Issue by cutecat5656** [yandevelop/Bea#42]
First it wasn't loading the new bereals-- I tried signing out and now I can't even sign in. please help

**Comment by MarcBisbal** [comment]
Same here, it shows an error when trying to log in

**Comment by yandevelop** [comment]
Weird issue. Just had this happen to me right now. I fixed this by updating BeReal to 2.10.2 (which obv does not fix it) then downgraded to 1.20.0. Now everything works fine again.

**Comment by cutecat5656** [comment]
How can we do this? Update and downgrade without jailbreak?

**Comment by yandevelop** [comment]
Just try installing a lower version from the Releases tab of Bea

**Comment by hogyoku** [comment]
I have tried downgrading/upgrading and clean installs with different versions but nothing seems to work. Could it be that they have implemented a similar ban to snapchats sideloading ?

**Comment by hogyoku** [comment]
![IMG_4680](https://github.com/yandevelop/Bea/assets/3275546/bcde02d7-39ed-4c88-b020-06c64648102b)

I’m getting the following error on the official side loaded version.

**Comment by yandevelop** [comment]
Alright, latest version seems to work halfway fine. It unblurs but the "Post late" button is still visible. However you won't be able to react anymore. I'll see what i can do in the future and will provide an update once i figure out how to remove the "Post  late" buttons.

**Comment by hogyoku** [comment]
> Alright, latest version seems to work halfway fine. It unblurs but the "Post late" button is still visible. However you won't be able to react anymore. I'll see what i can do in the future and will provide an update once i figure out how to remove the "Post late" buttons.

Nice work. Any news on the issue above ?

**Comment by cutecat5656** [comment]
I still can't seem to log in

**Comment by yandevelop** [comment]
To update you guys: The native unblur function I used in previous versions is apparently still present in newer BeReal versions but I can't seem to get a reference to it. My main idea was to "manually" calculate the memory address of the object I needed however I'm not able to do this since the object I'm getting is some Resolver object, bc apparently BeReal uses https://github.com/hmlongco/Resolver for dependency injection. I don't know if I'll get around this. If not I'll push an update that still unblurs the posts but will not have the full functionality. If anyone got any other ideas I'd be happy to hear them!

**Comment by cutecat5656** [comment]
When I log in it says an internal error has occurred, print and inspect the error details. Could you please help me resolve the issue?

**Comment by kckirch** [comment]
> When I log in it says an internal error has occurred, print and inspect the error details. Could you please help me resolve the issue?
> 
> 

Had this same issue. Contacted them and they were no help. It looks like they changed their 2fa services and broke it on older versions. I got logged back in by using a newer jailbroken device and using Apps Manager to backup that logged in session and moved it to this device. 
Don't have notifications currently but I think I can resolve that.

**Comment by yandevelop** [comment]
@kckirch it's actually bc using sideloaded Bea through AltStore or similar modifies the bundle id which results in the error you experienced. (See #24, or read [from here](https://github.com/yandevelop/Bea/issues/24#issuecomment-1937761069)) Using TrollStore (or anything that **doesn't** modify the bundle id) should work perfectly fine

**Comment by kckirch** [comment]
> @kckirch it's actually bc using sideloaded Bea through AltStore or similar modifies the bundle id which results in the error you experienced. (See #24, or read [from here](https://github.com/yandevelop/Bea/issues/24#issuecomment-1937761069)) Using TrollStore (or anything that **doesn't** modify the bundle id) should work perfectly fine

This issue I had was on a jailbroken device not side loaded tried through various versions also. 
But that makes more sense explaining what was occurring and why they just dump the actual error to the console. 
I would get the 2fa and enter just to get that generic error. 
After chatting with their support it seems their latest update had fixed the login issues which is true as I tested on another device on a higher iOS and the old versions <2.1.1 would give the login error. Latest BeReal. fixes the 2fa issue.

**Comment by yandevelop** [comment]
Alright, thanks for the information. Will update the IPA here too

**Comment by kckirch** [comment]
I'm going to do some more testing because when I did the App Manager backup to the older device I think some of the Plist stuff carried over from the newer version so when it loaded me in after the backup it gave me all sorts of weird messages about versions. Probably related to why I'm not getting notifications right now

**Comment by yandevelop** [comment]
@kckirch, please try this one: https://easyupload.io/8u2dtt. Couldn't test this myself for now unfortunately but that *might* fix the sideloading issues

**Comment by kckirch** [comment]
I wish I could test that fix, looks like bereal finally put the nail in the coffin for iOS 14 users. 2.1.1 is last iOS 14 version and you just get a fail to load profile. If you manage to get past that screen, you just can't post anymore. 

Not sure if anything could be done to get around this for that last 2.1.1 version. ![image](https://github.com/yandevelop/Bea/assets/40923277/bfa7f4d4-40bc-4136-b1bc-1f6b75020795)
