### ISSUE TITLE
Api error

### ISSUE THREAD

**Issue by ABTOPEMOHT** [yandevelop/Bea#46]
Iphone 12 pro max non jailed
Ios 17.5.1
Version of Bereal; tried all versions from github, only deb 1.3.8 to inject, from appdb also and nothing helps.
In the iphone settings cleared database and account, doesn't fix.
I installed this mod app with Sideloadly, but it says API Error Bad request when posting as BeFake.
Also it says that it's a 1.3.7 version in Bea settings. but I downloaded the latest
![photo_2024-06-08_19-20-01](https://github.com/yandevelop/Bea/assets/163136224/c2d7cebe-5f73-419d-bd46-4c204ca6cb56)
![photo_2024-06-08_19-20-05](https://github.com/yandevelop/Bea/assets/163136224/6e865588-03b2-4c70-8198-4cc57b241414)

**Comment by yandevelop** [comment]
I tested the upload functionality yesterday and it works just fine. Make sure you're leaving the caption and retake count empty (could cause issues)

**Comment by ABTOPEMOHT** [comment]
Thanks!!
