### ISSUE TITLE
problem with version 

### ISSUE THREAD

**Issue by mileda** [yandevelop/Bea#49]
In app when ı enter befake section ''there is new version of bea wanna update ?'' pops. But I sideloaded last version. 

In app it shows Bea 1.3.7 made with ''heart'' on downside version 2.14.2 testflight 18138 (production)

**Comment by mileda** [comment]
Yeap, deffinetly someting is off. I tryed to install 1.3.6 over it and the version changed to 1.36, then ı installed 1.38 but now it shows 1.3.7

**Comment by daboizmusic** [comment]
last commit was 10 month ago
I do not think that the project is still mentaied

**Comment by yandevelop** [comment]
Just forgot to bump version number in 1.3.8 iirc. I do not plan on further maintaining this project as of now. Maybe there will be an update at some time but I can't say for sure when

**Comment by mileda** [comment]
Hey I got the money, My bank trying to undersand that I’m not doing money laundry so don’t worry that money is not in lombo


________________________________
