### ISSUE TITLE
Verification Code can't send

### ISSUE THREAD

**Issue by FabiFNA** [yandevelop/Bea#5]
Whenever I enter a phone number it says that it can't send the verification code and therefore I don't recieve a code. Now entering the same number on normal bereal works. I downloaded the jailed ipa and used scarlet to sideload. I'm on iOS 16.3.1.

**Comment by yandevelop** [comment]
Hmm weird. Tried this right now on 2 devices with the jailed IPA (sideloaded using TrollStore), both worked. A workaround could be: verify your phone number with the normal BeReal IPA then sideload the jailed IPA over the normal BeReal IPA.

**Comment by FabiFNA** [comment]
How does it save the phone number? If I would be to enter the number on the non-tweaked ipa how would it save the login onto the tweaked ipa? Or do you mean to just limit the possible cause for the problem? However, I'll give it a try.

**Comment by FabiFNA** [comment]
So after some trying I still couldn't figure out what the problem was. Even an official ipa modded doesn't do the trick. Any suggestions?

**Comment by yandevelop** [comment]
Did you try to use the newest version compiled in Releases? I don't see the issue being caused by my tweak. I'd be happy to help but i dont know how

**Comment by FabiFNA** [comment]
Yea I tried using the newest version but the problem stills exists. Seems to be a me problem I don't think thats caused by your tweak. I'll try around a bit more and gather some info on what could cause the problem.
