### ISSUE TITLE
Cant install? Devices not supported

### ISSUE THREAD

**Issue by Bernarduzz** [yandevelop/Bea#7]
Trying to install jailed ipa on Iphone 14 pro ios 16.5 with both sideloadly and altstore and ran into this error. My device is not jailbreak so not sure if that will be an issue.

![CleanShot 2023-06-11 at 04 47 30](https://github.com/yandevelop/Bea/assets/126151183/044a6395-b6f9-43db-b30e-310f5549db04)

**Comment by yandevelop** [comment]
See #6
