### ISSUE TITLE
BeReals are blurred after first app start

### ISSUE THREAD

**Issue by binnichtaktiv** [yandevelop/Bea#8]
since version 1.2 was released the bereals don't update - it says no friend has posted anything but if i swipe down to this other view then the new bereals are shown. In addition, the bereals are not unblurred after the 1st and sometimes the 2nd app start . is it possible to fix this?🥲

**Comment by binnichtaktiv** [comment]
oh my bad i didn't see that version 1.2.1 was released. I will test it and then report whether it works or not

**Comment by yandevelop** [comment]
I have somehow only noticed that issue after release. It still does occur on 1.2.1 occasionally. I'll see what i can do

**Comment by binnichtaktiv** [comment]
![IMG_1160](https://github.com/yandevelop/Bea/assets/96953964/676f8c4a-f011-4350-b309-375fd1a0ff24)



Now with 1.2.1 it’s can see the bereals  but the button that says post a BeReal. is still there. And it still only shows in this view and not in the normal view where you can scroll down

**Comment by yandevelop** [comment]
Please use the workaround to restart the app 1-2 times until it's properly unblurred. I'm testing a fix right now
